stages:
  - test
  - deploy

image: docker

services:
  - docker:dind

test:
  stage: test
  script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - make mypy
    - make
    - make coverage
    # - docker-compose -f local.yml run --rm django mypy django_nustjs_rest_auth_example
    # - docker-compose -f local.yml run --rm django coverage run -m pytest
    # - docker-compose -f local.yml run --rm django coverage report
  coverage: '/TOTAL.+?(\d+)%/'
